export { setupRequestInterceptor } from './requestInterceptor'
export { setupResponseInterceptor } from './responseInterceptor'
export { get } from './get'
export { post } from './post'
export { put } from './put'
export { patch } from './patch'
export { del as delete } from './delete'
